version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mail-service
    networks:
      - email-service
  test-db:
    image: postgres:14.1-alpine
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mail-service
    networks:
      - email-service
networks:
  email-service: